accepted = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0",
    "ISC",
    "Unicode-DFS-2016"
]

workarounds = [
    "ring",
]

[ring]
accepted = [
    "OpenSSL"
]

[webpki.clarify]
license = "ISC"

[[webpki.clarify.files]]
path = "LICENSE"
license = "ISC"
checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a"
