accepted = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0",
    "ISC"
]

workarounds = [
    "ring",
]

[ring]
accepted = [
    "OpenSSL"
]

[encoding_rs.clarify]
license = "(Apache-2.0 OR MIT) AND BSD-3-Clause"

[[encoding_rs.clarify.files]]
path = "COPYRIGHT"
checksum = "11789f45bb180841cd362a5eee6789c68ddb573a11105e30768c308a6add0190"

[widestring.clarify]
license = "MIT OR Apache-2.0"

[[widestring.clarify.files]]
path = "LICENSES/MIT.txt"
license = "MIT"
checksum = "b85dcd3e453d05982552c52b5fc9e0bdd6d23c6f8e844b984a88af32570b0cc0"

[[widestring.clarify.files]]
path = "LICENSES/Apache-2.0.txt"
license = "Apache-2.0"
checksum = "074e6e32c86a4c0ef8b3ed25b721ca23aca83df277cd88106ef7177c354615ff"

[ct-logs.clarify]
license = "MIT OR Apache-2.0 OR ISC"

[[ct-logs.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2"

[[ct-logs.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "709e3175b4212f7b13aa93971c9f62ff8c69ec45ad8c6532a7e0c41d7a7d6f8c"

[[ct-logs.clarify.files]]
path = "LICENSE-ISC"
license = "ISC"
checksum = "7cfafc877eccc46c0e346ccbaa5c51bb6b894d2b818e617d970211e232785ad4"

[hyper-rustls.clarify]
license = "MIT OR Apache-2.0 OR ISC"

[[hyper-rustls.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2"

[[hyper-rustls.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "709e3175b4212f7b13aa93971c9f62ff8c69ec45ad8c6532a7e0c41d7a7d6f8c"

[[hyper-rustls.clarify.files]]
path = "LICENSE-ISC"
license = "ISC"
checksum = "7cfafc877eccc46c0e346ccbaa5c51bb6b894d2b818e617d970211e232785ad4"

[rustls-native-certs.clarify]
license = "MIT OR Apache-2.0 OR ISC"

[[rustls-native-certs.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2"

[[rustls-native-certs.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "709e3175b4212f7b13aa93971c9f62ff8c69ec45ad8c6532a7e0c41d7a7d6f8c"

[[rustls-native-certs.clarify.files]]
path = "LICENSE-ISC"
license = "ISC"
checksum = "7cfafc877eccc46c0e346ccbaa5c51bb6b894d2b818e617d970211e232785ad4"

[sct.clarify]
license = "MIT OR Apache-2.0 OR ISC"

[[sct.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2"

[[sct.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "709e3175b4212f7b13aa93971c9f62ff8c69ec45ad8c6532a7e0c41d7a7d6f8c"

[[sct.clarify.files]]
path = "LICENSE-ISC"
license = "ISC"
checksum = "7cfafc877eccc46c0e346ccbaa5c51bb6b894d2b818e617d970211e232785ad4"

[typenum.clarify]
license = "MIT OR Apache-2.0"

[[typenum.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "516b24e051bf5630880ebbd55c40a25ce9552ebaf8970a53e8976eb70e522406"

[[typenum.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "a825bd853ab71619a4923d7b4311221427848070ff44d990da39b0b274c1683f"

[webpki.clarify]
license = "ISC"

[[webpki.clarify.files]]
path = "LICENSE"
license = "ISC"
checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a"
