[package]
name = "credman"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.43"
url = "2.2.2"
keyring = "0.10.1"
authenticator = "0.3.1"
nom = "6.1"
sha2 = "0.8"
base64 = "0.13.0"
select = "0.5.0"
sxd-document = "~0.3"
sxd-xpath = "~0.4"
rusoto_core = "0.47.0"
rusoto_sts = "0.47.0"
rusoto_credential = "0.47.0"
structopt = "0.3"
structopt-derive = "0.4.15"
async-trait = "0.1.51"
thiserror = "1.0"
