[package]
name = "c9s"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
httpmock = "0.6"

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.43"
url = "2.2.2"
keyring = "0.10.1"
authenticator = "0.3.1"
nom = "7.0"
sha2 = "0.8"
base64 = "0.13.0"
select = "0.5.0"
sxd-document = "~0.3"
sxd-xpath = "~0.4"
rusoto_core = "0.47.0"
rusoto_sts = "0.47.0"
rusoto_credential = "0.47.0"
clap = "3.0.0-beta.4"
async-trait = "0.1.51"
thiserror = "1.0"
toml = "0.5.8"
dirs ="3.0.2"
rpassword = "5.0"
indicatif = "0.16.2"
simple_logger = "1.13.0"
log = "0.4.14"
regex = "1.5"
futures = "0.3"
