[package]
name = "c9s"
version = "0.1.0-alpha11"
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
httpmock = "0.6"

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.56"
url = "2.2.2"
base64 = "0.13.0"
select = "0.5.0"
aws-sdk-sts = "0.8.0"
aws-smithy-types-convert = { version = "0.38.0", features = ["convert-time"] }
time = { version = "0.3.7", features = ["formatting", "parsing"] }
clap = { version = "3.1.6", features = ["derive"] }
async-trait = "0.1.52"
toml = "0.5.8"
dirs = "4.0.0"
rpassword = "5.0"
log = "0.4.14"
regex = "1.5"
futures = "0.3"
tmuntaner-webauthn = { version = "0.1.0-alpha.11", features = ["full"] }
tmuntaner-keyring = "0.1.0-alpha.11"
quick-xml = "0.22.0"
