[package]
name = "wincred-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
windows = "0.21.1"

[dependencies]
windows = "0.21.1"
